[workspace.package]
edition = "2024"
license = "Apache-2.0"

[workspace]
members = ["auth", "tk"]
resolver = "3"

[workspace.dependencies]
anstyle = { version = "1.0.13", default-features = false }
anyhow = { version = "1.0", default-features = false }
assert_cmd = { version = "2", default-features = false }
base64 = { version = "0.22.0", default-features = false, features = ["std"] }
clap = { version = "4.5", features = ["std", "derive", "help", "usage", "error-context", "env"], default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
hpke = { version = "0.10", default-features = false, features = ["alloc", "p256", "serde_impls"] }
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa", "std"] }
rand_core = { version = "0.6.4", default-features = false, features = ["getrandom"] }
predicates = { version = "3", default-features = false }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "http2"] }
serde = { version = "1.0.219", default-features = false, features = ["std", "derive"] }
serde_json = { version = "1.0.140", default-features = false, features = ["std"] }
sha2 = { version = "0.10", default-features = false }
strum = { version = "0.27.2", default-features = false, features = ["derive", "std", "strum_macros"] }
tempfile = { version = "3.19.1", default-features = false }
thiserror = { version = "2", default-features = false }
tokio = { version = "=1.47.1", default-features = false }
toml = { version = "0.8", default-features = false, features = ["parse", "display"] }
tracing = { version = "0.1.41", default-features = false, features = ["attributes", "std"] }
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["ansi", "env-filter", "fmt"] }
turnkey_api_key_stamper = { git = "https://github.com/tkhq/rust-sdk.git", rev = "a64ca2b0d3178089221b648f3365eb67def95219" }
turnkey_client = { git = "https://github.com/tkhq/rust-sdk.git", rev = "a64ca2b0d3178089221b648f3365eb67def95219" }
turnkey_enclave_encrypt = { git = "https://github.com/tkhq/rust-sdk.git", rev = "a64ca2b0d3178089221b648f3365eb67def95219" }
uuid = { version = "1", default-features = false, features = ["serde", "std", "v4"] }
wiremock = { version = "0.6", default-features = false }
zeroize = { version = "1.8", default-features = false, features = ["alloc"] }
